### ISSUE TITLE
odds.fv does not calculate probability row-wise

### ISSUE THREAD

**Issue by dmitrijsc** [marcoblume/odds.converter#1]
Hi,

Lets assume we have a dataset with 2 columns "_home_" and "_away_" and we want to calculate the probability for each row.

```
Source: local data frame [6 x 2]

     home   away
1  1.5333 2.3750
2  1.5714 2.2500
3  1.7273 2.0000
4  1.6667 2.1000
5  1.6154 2.2000
..    ...    ...
```

if we try to use **_odds.fv**_ function on the data set

``` r
odds.fv(x$home, x$away, input = "dec", output = "prob")
```

we will get an exception

> Error in if (vig < 1) { : missing value where TRUE/FALSE needed

It happens because package assumes all odds belong to a single competition, when each row represents its own.

As a workaround we need to run this function row wise (for example, using dplyr) to make it working.

``` r
x %>% rowwise %>% mutate(prob_home = odds.fv(home, away, input = "dec", output = "prob")[1])
```

My suggestion is to rewrite the functions to allow vectors as inputs and return data frames as outputs. It will allow functions to operate on large data sets and not on single lines.

**Comment by marcoblume** [comment]
Hi,

would you be so kind to test new.odds.fv() that I just uploaded to Git to see if it solves your problem?
I have not fully tested it but the preliminary testing didn't throw any errors.

If new.odds.fv() works I will replace odds.fv() as it just adds functionality and no old cold should break.

Thanks for your input.

Marco

**Comment by dmitrijsc** [comment]
Hello Marco

It seems to pass my tests too.

Thanks!
Dmitrijs

**Comment by marcoblume** [comment]
Hi, 

after  more testing decided to move new.odds.fv() to odds.fv() as I could not find any bugs.

Marco

**Comment by dmitrijsc** [comment]
Great! Thanks for helping! It has also fixed another bug when one of the odds equals to 1.

**Comment by marcoblume** [comment]
Hi , 

could you share that potential bug with me in an example? I made some final changes to catch odds that to not equate to Vigged odds and update odds.fv().
Just want to make sure that testing is conclusive before I submit to cran.

Marco

**Comment by dmitrijsc** [comment]
There was a bug in the old version which is fixed now.

If you try to use the old version with the following example:

``` r
> odds.fv(1, 100, input = "dec", output = "prob")
Error in if (vig < 1) { : missing value where TRUE/FALSE needed
```

which works (?) in a new version

``` r
> new.odds.fv(1, 100, input = "dec", output = "prob")
X1 X100 
NA NA 
```

**Comment by marcoblume** [comment]
Thanks I actually reintroduced that bug again :) but thanks to you help was able to fix it and now return NA as expected.

 df <- data.frame(Home = c(1.5,1.8,1.9,1,2.05,2),
                  Away = c(2.9,2.2,2.05,100,2.05,2))

odds.fv(df,input = "dec",output = "prob")

```
      Home      Away
```

[1,] 0.6590909 0.3409091
[2,] 0.5500000 0.4500000
[3,] 0.5189873 0.4810127
[4,]        NA        NA
[5,]        NA        NA
[6,] 0.5000000 0.5000000

 odds.fv(df$Home,df$Away,input = "dec",output = "prob")
       df.Home   df.Away
[1,] 0.6590909 0.3409091
[2,] 0.5500000 0.4500000
[3,] 0.5189873 0.4810127
[4,]        NA        NA
[5,]        NA        NA
[6,] 0.5000000 0.5000000

 odds.fv(1,100,input="dec")
[1] NA

Hope this is the expected behavior for the users

**Comment by dmitrijsc** [comment]
Great! I will update the code from GitHub later today and let you know if anything breaks.
