### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by bkmontgom** [marcoblume/odds.converter#5]
Thanks for merging my PR!  I'm excited to be a contributor.

I think you should include the vig calculation from odds.fv as either its own function, or additional output.

How would you feel about a function to calculate the probability of a team winning a series?  Maybe pseries(prob_neutral_site, home(T, F), home_adv, games).  Does that fit in here?

**Comment by marcoblume** [comment]
> I think you should include the vig calculation from odds.fv as either its own function, or additional output.

What exactly do you mean by that? 

You want a function to replace this kind of  code? 

```
sum(odds.dec2prob(c(1.3,9,4)))
1.130342 
```


> How would you feel about a function to calculate the probability of a team winning a series? Maybe pseries(prob_neutral_site, home(T, F), home_adv, games). Does that fit in here?

Could add it but I don't quite think it fits into the theme of the package as I tried to keep the functionality ultra light at this stage. 
You would probably also need to add a play-schedule to the function to accommodate the NBA series for example which have a non alternating format.

**Comment by bkmontgom** [comment]
I understand on the series probability.
On the vig I mean:
odds.vig(1.3, 9, 4, input = "dec") would give (1.130342 - 1)/1.13042 = 0.1153119
or odds.vig(-110, -110) = 0.04545455
The intermediate variable in odds.fv you are calling vig is really overround + 1.

**Comment by marcoblume** [comment]
K that's a nice addition and simplifies the code
